import Prometheus from './prometheus.js'

let prometheus = new Prometheus()
export default prometheus

prometheus.addMetric("mogodb_up", 0)
prometheus.addMetric("mogodb_up", 0)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)
prometheus.addMetric("mogodb_up", 1)

prometheus.addMetric("mongodb_memory", 750)
prometheus.addMetric("mongodb_memory", 800)
prometheus.addMetric("mongodb_memory", 820)
prometheus.addMetric("mongodb_memory", 710)
prometheus.addMetric("mongodb_memory", 950)
prometheus.addMetric("mongodb_memory", 1020)
prometheus.addMetric("mongodb_memory", 1350)
prometheus.addMetric("mongodb_memory", 1100)
prometheus.addMetric("mongodb_memory", 1170)
prometheus.addMetric("mongodb_memory", 1200)

prometheus.addMetric("mongodb_operations", 20)
prometheus.addMetric("mongodb_operations", 15)
prometheus.addMetric("mongodb_operations", 10)
prometheus.addMetric("mongodb_operations", 4)
prometheus.addMetric("mongodb_operations", 20)
prometheus.addMetric("mongodb_operations", 80)
prometheus.addMetric("mongodb_operations", 150)
prometheus.addMetric("mongodb_operations", 80)
prometheus.addMetric("mongodb_operations", 95)
prometheus.addMetric("mongodb_operations", 40)

prometheus.addMetric("mongodb_diskspace", 800)
prometheus.addMetric("mongodb_diskspace", 780)
prometheus.addMetric("mongodb_diskspace", 700)
prometheus.addMetric("mongodb_diskspace", 650)
prometheus.addMetric("mongodb_diskspace", 500)
prometheus.addMetric("mongodb_diskspace", 330)
prometheus.addMetric("mongodb_diskspace", 310)
prometheus.addMetric("mongodb_diskspace", 290)
prometheus.addMetric("mongodb_diskspace", 270)
prometheus.addMetric("mongodb_diskspace", 240)

prometheus.addMetric("requests_total", 50)
prometheus.addMetric("requests_total", 55)
prometheus.addMetric("requests_total", 60)
prometheus.addMetric("requests_total", 65)
prometheus.addMetric("requests_total", 70)
prometheus.addMetric("requests_total", 75)
prometheus.addMetric("requests_total", 80)
prometheus.addMetric("requests_total", 85)
prometheus.addMetric("requests_total", 90)
prometheus.addMetric("requests_total", 150)

prometheus.addMetric("req_per_second", 10)
prometheus.addMetric("req_per_second", 12)
prometheus.addMetric("req_per_second", 11)
prometheus.addMetric("req_per_second", 15)
prometheus.addMetric("req_per_second", 45)
prometheus.addMetric("req_per_second", 25)
prometheus.addMetric("req_per_second", 5)
prometheus.addMetric("req_per_second", 17)
prometheus.addMetric("req_per_second", 26)
prometheus.addMetric("req_per_second", 20)

prometheus.addMetric("exception_count", 3)
prometheus.addMetric("exception_count", 3)
prometheus.addMetric("exception_count", 3)
prometheus.addMetric("exception_count", 4)
prometheus.addMetric("exception_count", 4)
prometheus.addMetric("exception_count", 26)
prometheus.addMetric("exception_count", 45)
prometheus.addMetric("exception_count", 75)
prometheus.addMetric("exception_count", 80)
prometheus.addMetric("exception_count", 110)

prometheus.addMetric("backend_ping", 30)
prometheus.addMetric("backend_ping", 32)
prometheus.addMetric("backend_ping", 28)
prometheus.addMetric("backend_ping", 250)
prometheus.addMetric("backend_ping", 700)
prometheus.addMetric("backend_ping", 1200)
prometheus.addMetric("backend_ping", 530)
prometheus.addMetric("backend_ping", 400)
prometheus.addMetric("backend_ping", 200)
prometheus.addMetric("backend_ping", 40)

prometheus.addMetric("frontend_response_time", 25)
prometheus.addMetric("frontend_response_time", 35)
prometheus.addMetric("frontend_response_time", 40)
prometheus.addMetric("frontend_response_time", 50)
prometheus.addMetric("frontend_response_time", 25)
prometheus.addMetric("frontend_response_time", 500)
prometheus.addMetric("frontend_response_time", 250)
prometheus.addMetric("frontend_response_time", 350)
prometheus.addMetric("frontend_response_time", 40)
prometheus.addMetric("frontend_response_time", 35)






